### ISSUE TITLE
Log in and log out and log in.

### ISSUE THREAD

**Issue by jackphuongvu** [lejard-h/flutter_facebook_connect#4]
The issues happens when I log in successfully, I log out. And I log in again. I can't access anymore.
it's always be in loading screen. 
Can you help me with this?
![image](https://user-images.githubusercontent.com/23715737/34970408-deb58222-faa6-11e7-8835-ef16445f88a7.png)

**Comment by jackphuongvu** [comment]
Can you try to log in and log out and log in again and more than one time?

**Comment by bramvbilsen** [comment]
@lunvjp Could you explain the behavior a bit more? My problem with this plugin is that it currently doesn't jump back to the app when a user tries to authenticate with Facebook. It works fine for all the times after that, but that is not the first impression I'd like...

**Comment by jackphuongvu** [comment]
So the problem is firstly I clicked the facebook's button. It redirected to "https://facebook.com/...", right? After I entered my Facebook's account. It automatically jump back to the app. OK?
Seem like Everything is OK right now.
ISSUE: But when I clicked log out's button. I clicked the facebook's button secondly.  It also redirected to "https://facebook.com/...". After I entered my Facebook's account, It DOESN'T jump back to the app.
It always show "localhost:/8080" forever.
You got the idea?
Thanks you for your time.

**Comment by bramvbilsen** [comment]
Alright, I think our problems are closely related so I won't make a new issue for it. Hopefully it gets fixed soon!

**Comment by jackphuongvu** [comment]
Cool.

**Comment by lejard-h** [comment]
Thanks for report, this should be fix in `0.0.4`. leave a comment here if you still have the problem

**Comment by jackphuongvu** [comment]
**I got this errors after running "futter packages get" with version 0.0.4. Can you help me with it?**


`D:\SOFTWARES\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in gymie...
Package flutter_facebook_connect has no versions that match >=0.0.4 <0.1.0 derived from:
- gymie depends on version ^0.0.4
---- Log transcript ----
FINE: Pub 1.25.0-dev.11.0
IO  : Spawning "cmd /c ver" in D:\WEB\Flutter\gymie\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | | 
    | | Microsoft Windows [Version 10.0.15063]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - flutter_webview_plugin ^0.0.9+1 from hosted (flutter_webview_plugin) (locked to 0.0.9+1)
    | - google_sign_in ^2.0.0 from hosted (google_sign_in) (locked to 2.0.0)
    | - flutter any from sdk (flutter) (locked to 0.0.40)
    | - firebase_auth ^0.4.0 from hosted (firebase_auth) (locked to 0.4.0)
    | - http ^0.11.3+14 from hosted (http) (locked to 0.11.3+14)
    | - flutter_facebook_connect ^0.0.4 from hosted (flutter_facebook_connect)
    | - shared_preferences ^0.3.1 from hosted (shared_preferences) (locked to 0.3.1)
IO  : Get versions from https://pub.dartlang.org/api/packages/flutter_facebook_connect.
IO  : HTTP GET https://pub.dartlang.org/api/packages/flutter_facebook_connect
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: D83C888A-1038-4E14-98E1-D6E11DF4AAE6
    | X-Pub-Environment: flutter_cli:get
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.25.0-dev.11.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/flutter_facebook_connect
    | took 0:00:00.758087
    | transfer-encoding: chunked
    | date: Sun, 21 Jan 2018 02:34:10 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: * start at root
SLVR: | firebase_auth 0.4.0 from hosted is locked
SLVR: | * select firebase_auth 0.4.0 from hosted
SLVR: | | flutter 0.0.40 from sdk is locked
SLVR: | | * select flutter 0.0.40 from sdk
SLVR: | | | collection 1.14.3 from hosted is locked
SLVR: | | | * select collection 1.14.3 from hosted
SLVR: | | | | flutter_test 0.0.18 from sdk is locked
SLVR: | | | | * select flutter_test 0.0.18 from sdk
SLVR: | | | | | * select pub itself
SLVR: | | | | | | args 0.13.7 from hosted is locked
SLVR: | | | | | | * select args 0.13.7 from hosted
SLVR: | | | | | | | async 1.13.3 from hosted is locked
SLVR: | | | | | | | * select async 1.13.3 from hosted
SLVR: | | | | | | | | barback 0.15.2+13 from hosted is locked
SLVR: | | | | | | | | * select barback 0.15.2+13 from hosted
SLVR: | | | | | | | | | boolean_selector 1.0.2 from hosted is locked
SLVR: | | | | | | | | | * select boolean_selector 1.0.2 from hosted
SLVR: | | | | | | | | | | charcode 1.1.1 from hosted is locked
SLVR: | | | | | | | | | | * select charcode 1.1.1 from hosted
SLVR: | | | | | | | | | | | convert 2.0.1 from hosted is locked
SLVR: | | | | | | | | | | | * select convert 2.0.1 from hosted
SLVR: | | | | | | | | | | | | crypto 2.0.2+1 from hosted is locked
SLVR: | | | | | | | | | | | | * select crypto 2.0.2+1 from hosted
SLVR: | | | | | | | | | | | | | flutter_webview_plugin 0.0.9+1 from hosted is locked
SLVR: | | | | | | | | | | | | | * select flutter_webview_plugin 0.0.9+1 from hosted
SLVR: | | | | | | | | | | | | | | glob 1.1.5 from hosted is locked
SLVR: | | | | | | | | | | | | | | * select glob 1.1.5 from hosted
SLVR: | | | | | | | | | | | | | | | google_sign_in 2.0.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | * select google_sign_in 2.0.0 from hosted
SLVR: | | | | | | | | | | | | | | | | http 0.11.3+14 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | * select http 0.11.3+14 from hosted
SLVR: | | | | | | | | | | | | | | | | | http_multi_server 2.0.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | * select http_multi_server 2.0.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | http_parser 3.1.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | * select http_parser 3.1.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | io 0.3.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | * select io 0.3.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | js 0.6.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | * select js 0.6.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | matcher 0.12.1+4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | * select matcher 0.12.1+4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | meta 1.1.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | * select meta 1.1.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | mime 0.9.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | * select mime 0.9.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | mockito 2.2.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | * select mockito 2.2.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | node_preamble 1.4.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | * select node_preamble 1.4.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | package_config 1.0.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | * select package_config 1.0.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | package_resolver 1.0.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | * select package_resolver 1.0.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | path 1.4.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select path 1.4.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | pool 1.3.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select pool 1.3.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | pub_semver 1.3.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select pub_semver 1.3.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | quiver 0.26.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select quiver 0.26.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shared_preferences 0.3.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shared_preferences 0.3.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf 0.7.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf 0.7.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_packages_handler 1.0.3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_packages_handler 1.0.3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_static 0.2.6 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_static 0.2.6 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | shelf_web_socket 0.2.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select shelf_web_socket 0.2.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | sky_engine 0.0.99 from path is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select sky_engine 0.0.99 from path
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_map_stack_trace 1.1.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_map_stack_trace 1.1.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_maps 0.10.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_maps 0.10.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | source_span 1.4.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select source_span 1.4.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | stack_trace 1.9.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select stack_trace 1.9.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | stream_channel 1.6.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select stream_channel 1.6.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | string_scanner 1.0.2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select string_scanner 1.0.2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | term_glyph 1.0.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select term_glyph 1.0.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | test 0.12.26 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select test 0.12.26 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | analyzer 0.30.0+4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select analyzer 0.30.0+4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | cli_util 0.1.2+1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select cli_util 0.1.2+1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | front_end 0.1.0-alpha.4.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select front_end 0.1.0-alpha.4.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | html 0.13.2+2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select html 0.13.2+2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | csslib 0.14.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select csslib 0.14.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | isolate 1.1.0 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select isolate 1.1.0 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | kernel 0.3.0-alpha.1.1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select kernel 0.3.0-alpha.1.1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | logging 0.11.3+1 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select logging 0.11.3+1 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | plugin 0.2.0+2 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select plugin 0.2.0+2 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | typed_data 1.1.4 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select typed_data 1.1.4 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | utf 0.9.0+3 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select utf 0.9.0+3 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | vector_math 2.0.5 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select vector_math 2.0.5 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | watcher 0.9.7+6 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select watcher 0.9.7+6 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | web_socket_channel 1.0.6 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select web_socket_channel 1.0.6 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | yaml 2.1.13 from hosted is locked
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | * select yaml 2.1.13 from hosted
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | inconsistent constraints on shared_preferences:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   flutter_facebook_connect 0.0.4 from hosted -> shared_preferences ^0.2.4+1 from hosted (shared_preferences)
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   gymie 0.0.0 (root) -> shared_preferences ^0.3.1 from hosted (shared_preferences)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.0.3 of flutter_facebook_connect doesn't match >=0.0.4 <0.1.0:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   gymie 0.0.0 (root) -> flutter_facebook_connect ^0.0.4 from hosted (flutter_facebook_connect)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.0.2 of flutter_facebook_connect doesn't match >=0.0.4 <0.1.0:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   gymie 0.0.0 (root) -> flutter_facebook_connect ^0.0.4 from hosted (flutter_facebook_connect)
SLVR: | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | version 0.0.1 of flutter_facebook_connect doesn't match >=0.0.4 <0.1.0:
    | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |   gymie 0.0.0 (root) -> flutter_facebook_connect ^0.0.4 from hosted (flutter_facebook_connect)
SLVR: BacktrackingSolver took 0:00:02.142325 seconds.
    | - Tried 1 solutions
    | - Requested 1 version lists
    | - Looked up 1 cached version lists
    | 
FINE: Resolving dependencies finished (2.2s).
ERR : Package flutter_facebook_connect has no versions that match >=0.0.4 <0.1.0 derived from:
    | - gymie depends on version ^0.0.4`

**Comment by lunvjp** [comment]
`<pre>asdasd</pre>`

**Comment by jackphuongvu** [comment]
Can you give me the suitable version of all Dependencies of flutter_facebook_connect's plugin?
Seem like I need to renew my version of all Dependencies ?

**Comment by lejard-h** [comment]
Did you try to remove `.pub`, `.packages` and `pubspec.lock` before doing pub get ?
