### ISSUE TITLE
get 'accessToken' as string (work with Firebase_auth)

### ISSUE THREAD

**Issue by jackphuongvu** [lejard-h/flutter_facebook_connect#6]
How can I get my accessToken to work with Firebase_auth?
`type 'FacebookOAuthToken' is not a subtype of type 'String' of 'accessToken' where`

```
FacebookOAuthToken token = await facebookConnect.login(
        force: force,
        fullscreen: fullscreen,
        scope: scope,
        cookie: cookie,
        storeToken: storeToken);
    if (onConnect != null) {
      onConnect(facebookConnect, token);
    }
```

This is Sign in with Facebook of Firebase_auth, so it should have accessToken as string
```
Future<FirebaseUser> signInWithFacebook(
      {@required String accessToken}) async {
    assert(accessToken != null);
    final Map<String, dynamic> data =
        await channel.invokeMethod('signInWithFacebook', <String, String>{
      'accessToken': accessToken,
    });
    final FirebaseUser currentUser = new FirebaseUser._(data);
    return currentUser;
  }
```

Thanks

**Comment by lejard-h** [comment]
Hello
you can get the access token inside [FacebookOAuthToken](https://www.dartdocs.org/documentation/flutter_facebook_connect/0.0.4/flutter_facebook_connect/FacebookOAuthToken-class.html)

`signInWithFacebook(token.access)`

**Comment by jackphuongvu** [comment]
Thanks..
