### ISSUE TITLE
Can't do "flutter packages get" command

### ISSUE THREAD

**Issue by biklas7** [lejard-h/flutter_facebook_connect#8]
Hi. I'm trying to use this package on my project but after runing the command `flutter packages get` I get the following error:

`Package flutter_facebook_connect has no versions that match >=0.0.4 <0.1.0 derived from:
my_app depends on version ^0.0.4`

**Comment by Iccr** [comment]
@biklas7 I faced the same problem. adding `flutter_facebook_connect: any ` solved for now. Idk whether its good or bad.

**Comment by biklas7** [comment]
@Iccr thanks for the tip, but now I'm facing another problem.

`PlatformException(error, Unable to find explicit activity class {com.myapp.myapp//com.flutter_webview_plugin.WebviewActivity}; have you declared this activity in your AndroidManifest.xml?, null)`

**Comment by lejard-h** [comment]
Sorry I have just updated the README, this package is not updated anymore. you should use [flutter_facebook_login](https://github.com/roughike/flutter_facebook_login) instead
